Repository Lv-581-Python-project/StockDashboard, pull requests merged in 2021-05, with the labels that each got.

#133 fixed get_data_for_time_period() method
  stock_dashboard_api/models/stock_model.py
Labels: backend

#130 129 alter db
  db/stock_dashboard/INSERT_DATA.sql
  db/stock_dashboard/data/dashboard.sql
  db/stock_dashboard/data/dashboard_has_stocks.sql
  db/stock_dashboard/schema/dashboard.sql
  db/stock_dashboard/schema/dashboard_has_stocks.sql
  stock_dashboard_api/utils/dashboard_hash_generator.py
Labels: database

#147 Added functional for tracking and loading missing data
  stock_dashboard_api/models/stock_model.py
  stock_dashboard_api/utils/constants.py
  tests/stock_dashboard_api/models/test_stock_model.py
Labels: backend

#156 Add updated diagram and clear README
  README.md
  documentation/diagrams/data_flow_diagram.png
Labels: database, documentation
